---
version: "2"
services:
  homer:
    image: b4bz/homer
    volumes:
      - ../homer:/www/assets:ro
    ports:
      - 8080:8080
    user: 1000:1000
    environment:
      - INIT_ASSETS=0
    networks:
      proxy:

networks:
  proxy:
    external:
      name: proxy
