---
version: "2"
services:
  homer:
    image: b4bz/homer
    volumes:
      - ./volumes/homer/assets:/www/assets
      - ./homer/config.yml:/www/assets/config.yml
    ports:
      - 8080:8080
    user: 1000:1000
    environment:
      - INIT_ASSETS=1
    networks:
      proxy:

networks:
  proxy:
    external:
      name: proxy
