version: "3.8"
services:
  app:
    image: "jc21/nginx-proxy-manager:latest"
    restart: unless-stopped
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - ./volumes/nginx_proxy_manager/data:/data
      - ./volumes/nginx_proxy_manager/letsencrypt:/etc/letsencrypt
    networks:
      proxy:

networks:
  proxy:
    external:
      name: proxy
